export const ACTION_UNDO = "UNDO";
export const ACTION_REDO = "REDO";
export const ACTION_MOVE_CANVAS = "MOVE_CANVAS";
export const ACTION_RECORD_STATE = "RECORD_STATE";
export const ACTION_CREATE_MODULE = "CREATE_MODULE";
export const ACTION_SELECT_MODULE = "SELECT_MODULE";
export const ACTION_MOVE_MODULE = "MOVE_MODULE";
export const ACTION_SELECT_PATH = "SELECT_PATH";
export const ACTION_SELECT_CONTROL_POINT = "SELECT_CONTROL_POINT";
export const ACTION_DESELECT_ALL = "DESELECT_ALL";



