export const ACTION_UNDO = "UNDO";
export const ACTION_REDO = "REDO";
export const ACTION_CREATE_WIDGET = "CREATE_WIDGET";
export const ACTION_MOVE_CANVAS = "MOVE_CANVAS";
export const ACTION_RECORD_STATE = "RECORD_STATE";
